spring:
  datasource:
    url: jdbc:postgresql://digihisab-dev-digihisab.f.aivencloud.com:16526/digi-hisab-dev
    username: avnadmin
    password: AVNS_Y_vGClGMbmvSseXEHY5
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      pool-name: HikariCP
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  threads:
    virtual:
      enabled: true

server:
  port: 8080
  servlet:
    context-path: /api/v1

logging:
  level:
    root: INFO
    com.yourpackage: DEBUG
    org.springframework.security: DEBUG
  file:
    path: logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
jwt:
  access-token-secret: "Da2E11qTolj3CdZPNc9SbOuFjRKOzqcxQ+fBq396RhoubMByk6GGyG3h3Gd5uHEX3i1JCd5LiB83/5cnLAy6qQ=="
  refresh-token-secret: "JoaT+zNTbNiqrI0HsBtcktTjp9t2243t+i4osnq80tu7TM5G/E9nJXmSYiao3N1Uu+zwbHkxVcsXsb2CuVLhGA=="
  expiration: 86400000
  refresh-token-expiration: 864000000


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /api-docs